// Generated by gencpp from file add_markers/marker_service.msg
// DO NOT EDIT!


#ifndef ADD_MARKERS_MESSAGE_MARKER_SERVICE_H
#define ADD_MARKERS_MESSAGE_MARKER_SERVICE_H

#include <ros/service_traits.h>


#include <add_markers/marker_serviceRequest.h>
#include <add_markers/marker_serviceResponse.h>


namespace add_markers
{

struct marker_service
{

typedef marker_serviceRequest Request;
typedef marker_serviceResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct marker_service
} // namespace add_markers


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::add_markers::marker_service > {
  static const char* value()
  {
    return "e5cce09bb285d3db26a9c9e57cf16f60";
  }

  static const char* value(const ::add_markers::marker_service&) { return value(); }
};

template<>
struct DataType< ::add_markers::marker_service > {
  static const char* value()
  {
    return "add_markers/marker_service";
  }

  static const char* value(const ::add_markers::marker_service&) { return value(); }
};


// service_traits::MD5Sum< ::add_markers::marker_serviceRequest> should match 
// service_traits::MD5Sum< ::add_markers::marker_service > 
template<>
struct MD5Sum< ::add_markers::marker_serviceRequest>
{
  static const char* value()
  {
    return MD5Sum< ::add_markers::marker_service >::value();
  }
  static const char* value(const ::add_markers::marker_serviceRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::add_markers::marker_serviceRequest> should match 
// service_traits::DataType< ::add_markers::marker_service > 
template<>
struct DataType< ::add_markers::marker_serviceRequest>
{
  static const char* value()
  {
    return DataType< ::add_markers::marker_service >::value();
  }
  static const char* value(const ::add_markers::marker_serviceRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::add_markers::marker_serviceResponse> should match 
// service_traits::MD5Sum< ::add_markers::marker_service > 
template<>
struct MD5Sum< ::add_markers::marker_serviceResponse>
{
  static const char* value()
  {
    return MD5Sum< ::add_markers::marker_service >::value();
  }
  static const char* value(const ::add_markers::marker_serviceResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::add_markers::marker_serviceResponse> should match 
// service_traits::DataType< ::add_markers::marker_service > 
template<>
struct DataType< ::add_markers::marker_serviceResponse>
{
  static const char* value()
  {
    return DataType< ::add_markers::marker_service >::value();
  }
  static const char* value(const ::add_markers::marker_serviceResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ADD_MARKERS_MESSAGE_MARKER_SERVICE_H
