// Generated by gencpp from file add_markers/marker_serviceRequest.msg
// DO NOT EDIT!


#ifndef ADD_MARKERS_MESSAGE_MARKER_SERVICEREQUEST_H
#define ADD_MARKERS_MESSAGE_MARKER_SERVICEREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace add_markers
{
template <class ContainerAllocator>
struct marker_serviceRequest_
{
  typedef marker_serviceRequest_<ContainerAllocator> Type;

  marker_serviceRequest_()
    : x(0.0)
    , y(0.0)
    , show_marker(false)  {
    }
  marker_serviceRequest_(const ContainerAllocator& _alloc)
    : x(0.0)
    , y(0.0)
    , show_marker(false)  {
  (void)_alloc;
    }



   typedef double _x_type;
  _x_type x;

   typedef double _y_type;
  _y_type y;

   typedef uint8_t _show_marker_type;
  _show_marker_type show_marker;





  typedef boost::shared_ptr< ::add_markers::marker_serviceRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::add_markers::marker_serviceRequest_<ContainerAllocator> const> ConstPtr;

}; // struct marker_serviceRequest_

typedef ::add_markers::marker_serviceRequest_<std::allocator<void> > marker_serviceRequest;

typedef boost::shared_ptr< ::add_markers::marker_serviceRequest > marker_serviceRequestPtr;
typedef boost::shared_ptr< ::add_markers::marker_serviceRequest const> marker_serviceRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::add_markers::marker_serviceRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::add_markers::marker_serviceRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace add_markers

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'visualization_msgs': ['/opt/ros/kinetic/share/visualization_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::add_markers::marker_serviceRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::add_markers::marker_serviceRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::add_markers::marker_serviceRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::add_markers::marker_serviceRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::add_markers::marker_serviceRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::add_markers::marker_serviceRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::add_markers::marker_serviceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "0a5c26925aaf6433a71a5dab8f87a83b";
  }

  static const char* value(const ::add_markers::marker_serviceRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x0a5c26925aaf6433ULL;
  static const uint64_t static_value2 = 0xa71a5dab8f87a83bULL;
};

template<class ContainerAllocator>
struct DataType< ::add_markers::marker_serviceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "add_markers/marker_serviceRequest";
  }

  static const char* value(const ::add_markers::marker_serviceRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::add_markers::marker_serviceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 x\n\
float64 y\n\
bool show_marker\n\
\n\
";
  }

  static const char* value(const ::add_markers::marker_serviceRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::add_markers::marker_serviceRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.show_marker);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct marker_serviceRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::add_markers::marker_serviceRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::add_markers::marker_serviceRequest_<ContainerAllocator>& v)
  {
    s << indent << "x: ";
    Printer<double>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<double>::stream(s, indent + "  ", v.y);
    s << indent << "show_marker: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.show_marker);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ADD_MARKERS_MESSAGE_MARKER_SERVICEREQUEST_H
