// Generated by gencpp from file add_markers/marker_serviceResponse.msg
// DO NOT EDIT!


#ifndef ADD_MARKERS_MESSAGE_MARKER_SERVICERESPONSE_H
#define ADD_MARKERS_MESSAGE_MARKER_SERVICERESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace add_markers
{
template <class ContainerAllocator>
struct marker_serviceResponse_
{
  typedef marker_serviceResponse_<ContainerAllocator> Type;

  marker_serviceResponse_()
    : marker_updated(false)  {
    }
  marker_serviceResponse_(const ContainerAllocator& _alloc)
    : marker_updated(false)  {
  (void)_alloc;
    }



   typedef uint8_t _marker_updated_type;
  _marker_updated_type marker_updated;





  typedef boost::shared_ptr< ::add_markers::marker_serviceResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::add_markers::marker_serviceResponse_<ContainerAllocator> const> ConstPtr;

}; // struct marker_serviceResponse_

typedef ::add_markers::marker_serviceResponse_<std::allocator<void> > marker_serviceResponse;

typedef boost::shared_ptr< ::add_markers::marker_serviceResponse > marker_serviceResponsePtr;
typedef boost::shared_ptr< ::add_markers::marker_serviceResponse const> marker_serviceResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::add_markers::marker_serviceResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::add_markers::marker_serviceResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace add_markers

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'visualization_msgs': ['/opt/ros/kinetic/share/visualization_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::add_markers::marker_serviceResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::add_markers::marker_serviceResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::add_markers::marker_serviceResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::add_markers::marker_serviceResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::add_markers::marker_serviceResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::add_markers::marker_serviceResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::add_markers::marker_serviceResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ca8098ed83e8add35e0051a9937647c5";
  }

  static const char* value(const ::add_markers::marker_serviceResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xca8098ed83e8add3ULL;
  static const uint64_t static_value2 = 0x5e0051a9937647c5ULL;
};

template<class ContainerAllocator>
struct DataType< ::add_markers::marker_serviceResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "add_markers/marker_serviceResponse";
  }

  static const char* value(const ::add_markers::marker_serviceResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::add_markers::marker_serviceResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n\
bool marker_updated\n\
\n\
";
  }

  static const char* value(const ::add_markers::marker_serviceResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::add_markers::marker_serviceResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.marker_updated);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct marker_serviceResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::add_markers::marker_serviceResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::add_markers::marker_serviceResponse_<ContainerAllocator>& v)
  {
    s << indent << "marker_updated: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.marker_updated);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ADD_MARKERS_MESSAGE_MARKER_SERVICERESPONSE_H
